vat_and_excise:
  - "305"
  - "VTA"
  - "VTE"
  - "VTS"
  - "VTZ"
  - "306"
  - "DAA"
  - "DAB"
  - "DAC"
  - "DAE"
  - "DAI"
  - "DBA"
  - "DBB"
  - "DBC"
  - "DBE"
  - "DBI"
  - "DCA"
  - "DCC"
  - "DCE"
  - "DCH"
  - "DDA"
  - "DDB"
  - "DDC"
  - "DDD"
  - "DDE"
  - "DDF"
  - "DDG"
  - "DDJ"
  - "DEA"
  - "DFA"
  - "DFB"
  - "DFC"
  - "DGC"
  - "DHA"
  - "DHC"
  - "DHE"
  - "DHG"
  - "EBA"
  - "EBB"
  - "EBJ"
  - "EDA"
  - "EDB"
  - "EDJ"
  - "EEA"
  - "EEF"
  - "EFA"
  - "EGA"
  - "EGB"
  - "EGJ"
  - "EHI"
  - "EXA"
  - "EXB"
  - "EXC"
  - "EXD"
  - "FAA"
  - "FAE"
  - "FAI"
  - "FBC"
  - "FBG"
  - "FCC"
  - "LBJ"
  - "LDA"
  - "LEA"
  - "LEF"
  - "LFA"
customs_duties: 
  - "103"
  - "105"
  - "109"
  - "110"
  - "106"
  - "142"
  - "145"
  - "112"
  - "115"
  - "117"
  - "119"
  - "141"
  - "489"
  - "490"
  - "651"
  - "652"
hide_me:
  - "430"
  - "431"
  - "442"
  - "447"
  - "464"
  - "481"
  - "482"
  - "483"
  - "484"
import_controls:
  - "277"
  - "350"
  - "351"
  - "352"
  - "353"
  - "354"
  - "355"
  - "357"
  - "358"
  - "359"
  - "360"
  - "361"
  - "362"
  - "363"
  - "410"
  - "465"
  - "474"
  - "475"
  - "705"
  - "707"
  - "710"
  - "711"
  - "712"
  - "713"
  - "714"
  - "719"
  - "722"
  - "724"
  - "728"
  - "730"
  - "745"
  - "746"
  - "747"
  - "748"
  - "750"
  - "755"
  - "760"
  - "761"
  - "774"
export_controls:
  - "278"
  - "467"
  - "473"
  - "476"
  - "478"
  - "479"
  - "706"
  - "708"
  - "709"
  - "715"
  - "716"
  - "717"
  - "718"
  - "725"
  - "735"
  - "740"
  - "749"
  - "751"
  - "766"
meursing:
  - "672"
  - "673"
  - "674"
quotas:
  - "122"
  - "123"
  - "143"
  - "146"
  - "653"
  - "654"
remedies:
  - "551"
  - "552"
  - "553"
  - "554"
  - "555"
  - "561"
  - "564"
  - "565"
  - "566"
  - "570"
  - "695"
  - "696"
  